// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/(admin)/admin/ai-tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/ai-tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/ai-tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/apikeys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/apikeys">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/apikeys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/categories/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/categories/add">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/categories/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/chats">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/credits">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/no-permission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/no-permission">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/no-permission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/permissions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/posts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/posts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/posts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/posts/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/posts/add">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/posts/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/roles/[id]/edit-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/roles/[id]/edit-permissions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/roles/[id]/edit-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/roles/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/roles/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/roles/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/settings/[tab]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings/[tab]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/settings/[tab]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/users/[id]/edit-roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users/[id]/edit-roles">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/users/[id]/edit-roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/users/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/users/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(auth)/no-permission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/no-permission">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(auth)/no-permission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(auth)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-in">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(auth)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(auth)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-up">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(auth)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(chat)/chat/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chat/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(chat)/chat/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(chat)/chat/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chat/history">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(chat)/chat/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(chat)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(chat)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(docs)/docs/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/docs/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(docs)/docs/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/(ai)/ai-audio-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-audio-generator">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/(ai)/ai-audio-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/(ai)/ai-chatbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-chatbot">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/(ai)/ai-chatbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/(ai)/ai-image-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-image-generator">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/(ai)/ai-image-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/(ai)/ai-music-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-music-generator">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/(ai)/ai-music-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/(ai)/ai-video-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-video-generator">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/(ai)/ai-video-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/ai-tasks/[id]/refresh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/activity/ai-tasks/[id]/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/ai-tasks/[id]/refresh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/ai-tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/activity/ai-tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/ai-tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/activity/chats">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/feedbacks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/activity/feedbacks">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/feedbacks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/blog/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/category/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/blog/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/apikeys/[id]/delete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/apikeys/[id]/delete">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/apikeys/[id]/delete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/apikeys/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/apikeys/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/apikeys/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/apikeys/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/apikeys/create">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/apikeys/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/apikeys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/apikeys">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/apikeys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/billing/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/billing/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/billing/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/billing/retrieve/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/billing/retrieve">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/billing/retrieve/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/credits">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/invoices/retrieve/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/invoices/retrieve">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/invoices/retrieve/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/security">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/showcases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/showcases">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/showcases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/import">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/report/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/report/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/report/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/yesterday-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/yesterday-ai">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/yesterday-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/yesterday-bilibili/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/yesterday-bilibili">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/yesterday-bilibili/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/yesterday-youtube/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/yesterday-youtube">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/yesterday-youtube/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/yesterday/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community/yesterday">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/yesterday/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/community/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/community/import">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/community/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ads.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ads.txt">> = Specific
  const handler = {} as typeof import("../../../src/app/ads.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/query">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/info">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/new/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/new">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/new/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/config/get-configs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/get-configs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/config/get-configs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/docs/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/docs/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/send-email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/notify/[provider]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/notify/[provider]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/notify/[provider]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/storage/upload-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storage/upload-image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/storage/upload-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/get-user-credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/get-user-credits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/get-user-credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/get-user-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/get-user-info">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/get-user-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(chat)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(chat)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(docs)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(docs)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/activity/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/activity/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/(landing)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/(landing)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/community/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/community">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/community/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
